# Generated by Django 4.2 on 2024-11-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('info', 'Information'), ('warn', 'Warning'), ('alert', 'Alert'), ('Invitation', 'Invitation'), ('Accept', 'Accept'), ('Application', 'Application')], max_length=50),
        ),
    ]
