# Generated by Django 4.2 on 2024-11-11 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat_count',
            field=models.IntegerField(help_text='Le nombre minimal de places doit être 1.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
