# Generated by Django 4.2 on 2024-11-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0005_reservation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Payment_Method',
            field=models.CharField(choices=[('online_payment', ' online_payment'), ('cash_payment', 'cash_payment')], max_length=20),
        ),
    ]
