# Generated by Django 5.1.3 on 2024-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('info', 'Information'), ('warn', 'Warning'), ('alert', 'Alert'), ('Invitation', 'Invitation'), ('Accept', 'Accept'), ('Decline', 'Decline'), ('Application', 'Application'), ('Reservation', 'Reservation'), ('Reminder', 'Reminder')], max_length=50),
        ),
    ]
