# Generated by Django 5.1.3 on 2024-11-09 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='conducteur_contact',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Le contact du conducteur est composé de 8 chiffres.', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='places_disponibles',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=4, message='le nombre de place doit etre inférieur ou égale à 4')]),
        ),
    ]
