# Generated by Django 5.1.3 on 2024-11-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_users_nature_users_role'),
        ('trajets', '0002_alter_trajet_conducteur_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.users'),
        ),
    ]
