# Generated by Django 4.2 on 2024-11-04 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_carpools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpool',
            name='description',
            field=models.TextField(blank=True, help_text="Description of the carpool's purpose."),
        ),
        migrations.AddField(
            model_name='carpool',
            name='rules',
            field=models.TextField(blank=True, help_text='Rules for the carpool.'),
        ),
        migrations.AlterField(
            model_name='carpool',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
