# Generated by Django 5.1.3 on 2024-11-24 23:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0002_initial'),
        ('group', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupridereservation',
            name='accept_as_group',
        ),
        migrations.RemoveField(
            model_name='groupridereservation',
            name='group',
        ),
        migrations.AddField(
            model_name='carpool',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupridereservation',
            name='carpool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.carpool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupridereservation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_reservations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupridereservation',
            name='reservation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 0, 54, 55, 804623, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='groupridereservation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trip.trajet'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GroupReservationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='sent', max_length=20)),
                ('notification_time', models.DateTimeField(auto_now_add=True)),
                ('group_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupridereservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupReservationParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('group_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupridereservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupridereservation',
            name='members',
            field=models.ManyToManyField(through='group.GroupReservationParticipants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReservationParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('group_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupridereservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RideReservationParticipants',
        ),
    ]
