# Generated by Django 5.1.3 on 2024-11-24 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_groupridereservation_accept_as_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupridereservation',
            name='reservation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 0, 58, 39, 729716, tzinfo=datetime.timezone.utc)),
        ),
    ]
