# Generated by Django 5.1.3 on 2024-11-25 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_groupridereservation_reservation_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupridereservation',
            name='reservation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 1, 8, 4, 436271, tzinfo=datetime.timezone.utc)),
        ),
    ]
