# Generated by Django 5.1.3 on 2024-11-25 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_groupridereservation_reservation_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupridereservation',
            name='reservation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 15, 12, 59, 932378, tzinfo=datetime.timezone.utc)),
        ),
    ]
