# Generated by Django 5.1.3 on 2024-12-15 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_alter_groupridereservation_reservation_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Group image', null=True, upload_to='carpool_images/'),
        ),
        migrations.AlterField(
            model_name='groupridereservation',
            name='reservation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 16, 32, 22, 589695, tzinfo=datetime.timezone.utc)),
        ),
    ]
