# Generated by Django 5.1.3 on 2024-12-15 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_carpool_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupridereservation',
            name='reservation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 16, 58, 8, 459160, tzinfo=datetime.timezone.utc)),
        ),
    ]
