# Generated by Django 5.1.3 on 2024-12-15 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_groupridereservation_reservation_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='image_data',
            field=models.BinaryField(blank=True, help_text='Binary data of the generated image', null=True),
        ),
        migrations.AlterField(
            model_name='groupridereservation',
            name='reservation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 18, 35, 6, 787896, tzinfo=datetime.timezone.utc)),
        ),
    ]
