# Generated by Django 5.1.3 on 2024-12-15 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_carpool_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupridereservation',
            name='reservation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 19, 14, 50, 369297, tzinfo=datetime.timezone.utc)),
        ),
    ]
