# Generated by Django 4.2 on 2024-12-15 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_carpool_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupridereservation',
            name='reservation_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 20, 16, 19, 627532, tzinfo=datetime.timezone.utc)),
        ),
    ]
